//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpAct
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turnover_equipm
    {
        public int ID_turnover_equipm { get; set; }
        public Nullable<System.DateTime> Date_turnover { get; set; }
        public Nullable<int> Count_equipm { get; set; }
        public Nullable<int> ID_equipment { get; set; }
        public Nullable<int> ID_type_turnover { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Type_turnover Type_turnover { get; set; }
    }
}
